services:
  app:
    build:
      context: .
    command:
      "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
  
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
